### PR TITLE
Carey Baldwin

### PR DESCRIPTION
**Pull request by careybaldwin02**
- [x] Take the steps necessary to create a package.json to keep a record of all dependencies.

- [x] Configure an npm script named "start" that will execute your code using nodemon so that the server restarts on changes. Make nodemon be a development time dependency only, it shouldn't be deployed to production.

- [x] Design and build a set of endpoints listed below.

- [x] /register
- [x] /login
- [x] /users

- [x] Use Postman to test the API as you work through the exercises.

- [x] add express-session and adjust login and get request to allow session-specific access.

### CODE REVIEW

**Comment by kelfro** [comment]
Looking good! You probably want to use a bigger number for the hash (>=10). Love the comments - helps to keep everything orderly and easy to read.

**Comment by careybaldwin02** [comment]
> Looking good! You probably want to use a bigger number for the hash (>=10). Love the comments - helps to keep everything orderly and easy to read.

OK, sounds great.  Thanks!

**Comment by careybaldwin02** [comment]
Accidentally closed PR, trying to re-open here.

**Comment by kelfro** [comment]
Nice job! I tested everything on Postman and it all works as it should - it won't let me see the users unless I am registered and currently logged in. Code is readable and commits are frequent and informative.
I rate this a 2 - great work!

**Pull request closed without merging**
